services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT}
      AZURE_OPENAI_KEY: ${AZURE_OPENAI_KEY}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
    restart: unless-stopped
    ports:
      - 8080:8080
